### PR TITLE
UI and usability tweaks

### PR DESCRIPTION
**Pull request by ayumi**
screen shot 2016-06-15 at 14 54 54

### CODE REVIEW

**Comment by evansagge** [comment]
While we're at this, would it be possible to display the git revision for the image?

**Comment by ayumi** [comment]
The thing to show would probably be the docker image hash and timestamp, which we could match to our app's git commit hash.

**Comment by ayumi** [comment]
Adding image hash is a little out of scope for this PR so I'll open a separate one.

**Comment by tombenner** [comment]
LGTM! 👍 

Diggin' the dynamic command syntax improvement in particular!

**Pull request merged**
